CODE_TOGGLE_SWITCH = 'SwitchToggle'
CODE_TURN_ON_SWITCH = 'SwitchOn'
CODE_TURN_OFF_SWITCH = 'SwitchOff'

CODE_FAN_OFF = 'FanOff'
CODE_FAN_LOW = 'FanLow'
CODE_FAN_MEDIUM = 'FanMedium'
CODE_FAN_HIGH = 'FanHigh'
